name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --enable-code-coverage
      
    - name: Generate coverage report
      run: |
        xcrun llvm-cov export \
          .build/debug/syndromePackageTests.xctest/Contents/MacOS/syndromePackageTests \
          -instr-profile .build/debug/codecov/default.profdata \
          -format="lcov" > coverage.lcov
      continue-on-error: true
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
      continue-on-error: true

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v

  test-ios:
    name: Test on iOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build for iOS
      run: |
        xcodebuild build \
          -scheme syndrome \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath .build/ios \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
      continue-on-error: true
      
    - name: Test on iOS
      run: |
        xcodebuild test \
          -scheme syndrome \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath .build/ios \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
      continue-on-error: true

  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run SwiftLint
      run: |
        brew install swiftlint
        swiftlint --reporter github-actions-logging
      continue-on-error: true