name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build
      run: swift build -c release
      
    - name: Run tests
      run: swift test -c release
      
    - name: Create Release Notes
      id: release_notes
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "# Release Notes for v$VERSION" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        # Extract the relevant section from CHANGELOG.md
        sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$ d' >> RELEASE_NOTES.md || echo "No changelog entry found for v$VERSION" >> RELEASE_NOTES.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update Documentation
      run: |
        swift package generate-documentation
      continue-on-error: true